the god in her veins
====================

The God in Her Veins

by Raven Morier

She'd forgotten her lunch and It wanted her to know.

CONSUME FLESH

Her stomach rumbled and she looked at the chocolate bars in front of her
cash. Overpriced and not remotely healthy.

FLESH

Chips weren't really better. Jerky?

FLESH

She stepped around the counter.

“Natt! Where you are going?” Her Slavic boss asked from the office. The
door was cracked open so he could call out to her without actually
leaving the room.

“Nowhere.” She looked around but the store was still deserted except for
the two of them. “Just going to face the jerky.”

“What if customer come and see you not behind cash?”

CONSUME FLESH

“Then they get upset and not come back,” she mimed his accent as she
grabbed a package of beef jerky.

“Exactly. Behind cash, Natt. Check cigarettes.”

She scanned her food and set the money in the till.

FLESH

“All right, all right.”

“Who you are talking to, Natt?”

“Just myself.” She tore open the package and devoured its contents.

FRESHER

Not happening here, friend.

FRESHER

She sighed. It didn't seem to like salted meat, but at least she wasn't
quite so hungry.

The God in her veins promised power and wisdom, but mostly It
just demanded meat. Her memory of a life without It was cloudy—It still
hadn't even fixed that—and she couldn't remember what it was like to be
normal. She couldn't clearly remember more than the past year, which she
had spent listening to demands for meat while working at a convenience
store.

She had vague memories of her past life but couldn't prove they weren't
just television shows she'd once watched. Had she actually driven around
solving supernatural mysteries? Had her parents actually been killed in
front of her? Were there actually aliens infiltrating world governments?

She didn't seem to have parents so the second seemed the most likely.

CONSUME FLESH

A customer walked in. The older man, dressed like an anachronistic Texan
rancher, gave a nod before making his way to the magazines. She nodded
back, strumming her fingers on the counter. He was reading one without
purchasing it, but Natt didn't care enough to stop him.

SPREAD ME

“What?” she whispered. The man coughed and turned a page.

SPREAD TO SURVIVE

This was new.

How?

BLESS WITH BLOOD

I can't really do that in a store. My store. Where I work.

BLESS WITH BLOOD

Ugh, later.

BLESS WITH BLOOD

It had never said this before and she didn't know what it meant. The
phrase felt intimate and messy, something she wasn't interested in
performing on this strange man.

He coughed again, making her uneasy. Weird sicknesses were popping up
all the time. He eventually recovered enough to put back the magazine
and grab a case of beer.

CONSUME FLESH

He looked through the chips, shaking his head at each one. Or perhaps
just at each one's price. Natt clenched her fists. She wanted to hit
something. She wanted to tackle someone and rip out their throat like
a lioness hunting a gazelle.

CONSUME FLESH

He eventually came to the front, setting the beer down and looking
pointedly at her nearly-flat chest.

“Will that be all?” she asked between gritted teeth.

“The end is comin', girl.”

“Sure.” She scanned the beer and gestured at the price on the screen.

“None can be safe from the truth.”

SPREAD TO SURVIVE

He passed her a $20 bill and she gave him the change wordlessly. He
nodded and left with his beer.

What is your deal?

SPREAD TO SURVIVE

Give me something else. Words.

CONSUME FLESH.

She groaned and leaned against the back wall. It was another tedious
hour before Cor came in for his shift. A few people came into the store.
Some spoke meaningless pleasantries, some warned of a fast-approaching
reckoning, and the rest bitched about prices. Sprinkled against this
mosaic of customer service transactions were the God’s demands for meat
and blood rituals. It seemed keen on the idea without explaining any of
the details.

When Cor walked in the door she gave a dramatic bow. “My savior.”

“What up, Natt, you're free. Be free.” He swayed behind the counter and
leaned against the back wall. He wore prescription sunglasses and had
the complexion of a teenage vampire. He was somewhere between ironically
awful at life and just regular awful at life, and Natt could never say
which parts of him were from which half.

“Corvin, is you?”

“I'm here, boss. The business is saved!” He gave her a ragged smile and
she thought he rolled his eyes. “Anything exciting?” He mumbled.

“Nope. Literally nothing. Oh, wait, no, there are some creeps in town
who are talking about the truth coming for us. Or the apocalypse. Or
something.”

He snorted. “Yeah, got that yesterday. Weird religious freaks, although
I didn't see any crosses on 'em or anything. Must be some convention in
town.”

“In this town?”

“Who knows? Maybe we missed an alien landing and they're alien nerds. Or
they're aliens.”

CONSUME FLESH

Her stomach growled and Natt said, “I'm sure we can get to the bottom of
this but I'm starved.”

“Well, I'll update you if any aliens come lookin' for booze.”

“Thanks. I'm going for break!” She called back and got a garbled phrase
that was presumably an acknowledgment.

She waved at Cor and walked up the street to a chip stand. The streets
were as dead as usual, although the people she did notice seemed
strange. She couldn't decide if she just didn't know her neighbors, or
if they were from out of town.

FLESH

I'm on it.

She bought a triple burger with bacon and the God in her veins seemed
appeased. She felt rather than heard a contented vibration, rather like
a cat's purr. As she finished the burger and started appreciating the
beautiful day in relative silence, she decided to try asking it, How do
I bless with blood?

FIND A HOST AND JOIN THE HOST TO US

How?

FIND A HOST

What sort of host?

UNINFECTED BY METAL, TREES, OR LIES

I don't understand any of that.

CONSUME FLESH

I literally just did!

CONSUME FLESH

Natt got back up and threw out her garbage. Across the street was a
small bookshop she liked to browse, but first she pulled out a pocket
mirror and made sure her face was clean and as pretty as it could get.
She didn't care enough to put on makeup, so she shrugged and decided she
was “as good as it gets”.

As she entered, a bell above the door announced her arrival. Rose peeked
out from behind a shelf, smiled, and vanished again. Her hair was dyed a
lovely purple that matched her purple lace collar. Her face was
strangely familiar yet utterly unplaceable; Natt had never gotten the
courage to ask if they'd met somewhere else, but the other woman had
never acted as if they had.

Violin music played from a speaker in the front and the place was empty
except for them.

“Busy day?” Natt asked.

“Busy as ever. I think sales burst into the double digits today.”

Natt looked at the nearest shelf, barely reading the titles. She always
left with a romance novel, something she could read in a night. But she
still liked the look and smell of all these old books living together,
and the covers of things she'd never heard of and would likely never
read.

“Did you end up seeing that frog exhibit?”

Rose reappeared from behind the shelf, one arm full of books. “Yeah, it
was pretty good. Worth seeing once, certainly. You should check it out
before it leaves town.”

“Yeah, maybe.” She picked up a book and had to grin at the cover. A
dreadful fantasy book featuring the titled hero Baron Knight as he
fought off monsters and won the affection of some swooning maiden who
was... from the future?

“They're actually all right,” Rose said, nodding at it. “If you can get
past some groan-worthy male power-fantasy crap and the occasional
explosion of flowery prose.”

“I'm not sure I could get past that.”

“Well, not for everyone. There's a romance between him and the girl,
though.” She wiggled her eyebrows and Natt blushed, looking back to the
cover.

“Yeah, but it's hardly the focus, is it?”

BLESS WITH BLOOD

“No, not really. It's pretty forced.” She placed books on the shelves to
either side of them and Natt swallowed, trying to moisten her
suddenly-dry mouth.

“Hey, are you... doing anything tonight?”

“Dinner with my sister.” She frowned, but didn't look up from the books.
“Why do you ask?”

“Oh, ah, no reason. So you recommend this book, then?”

A smile. “Yeah. It's that ‘so bad it's good’ sort of thing. Lots of neat
concepts, though, particularly the demonology.”

“Well, I'll see if Baron Knight is all he's cracked up to be then.” She
held up the book as Rose placed her last one down.

“Just a dollar for this piece of art.”

Natt pulled out a pile of coins and handed her 4 quarters, smiling
apologetically. “I'll tell you how it is.”

“You better!” The other woman disappeared into the back and Natt left
with a sigh.

BLESS WITH BLOOD

“I'm trying to get someone, but I'm... not very good at it.” Or a lot of
things, she thought.

She returned to work 5 minutes early. Cor looked as if he hadn't so much
as moved except to grab a magazine. Something about scandals and famous
people.

“What up, Cor,” she said, swaying like a flamboyant drunk. He waved a
hand dismissively.

“Boss is gone, so I've just been here.”

“Any more freaks?”

“Naw. Well, nobody strange in the strange sort of way at least. Just the
usual sort of hicks and yuppies.”

BLESS WITH BLOOD

She grimaced. Cor was in the uncanny valley of intimacy, neither a
stranger nor someone with whom she shared any real spiritual connection.
To do something involving bodily fluids, she felt that it had to be on
either end of the spectrum or it would just be weird. Still, he did seem
to meet a lot of people...

“You going out tonight?”

“Probably,” he said, looking taken aback. “Are you thinking of actually
doing something outside work and home?”

“Shut up, and yes. Where are you going tonight?”

“I'm going down to the harbour.”

“Harbour? Ugh.”

“Fine, don't come.”

“No, no, just... the harbour?”

“Yeah, cheap bars, cheap drinks, cheap people.”

“All right, fine. I'm in.”

“Sweet. I'm off at 4 and going down at 5.”

“Isn't... that early?”

“Natt, please, trust me. You want to get a head start on these things.”

“All right.”

He nodded at the book she still had in her hands and asked, “You're
reading Baron Knight?”

“Just bought it. Is it any good?”

“It's the greatest and stupidest work of our times. Neat magic
mechanics, though.”

“Yeah, Rose was saying something like that—she's the girl who works at
the book store. She mentioned the demonology.”

“Yeah. Almost believable, you know? If it isn't aliens in the
government, it must be some sort of gooey demons that possess wolves and
bears and stuff.”

“How would wolves and bears infiltrate government?”

“By switching hosts, obviously.” He gave her what was probably a pointed
look, but with his glasses on it was largely lost on her. With a shrug,
he picked up his magazine and kept reading.

She looked at the book in her hands and frowned. It completely
transected her limited social life and it made her uncomfortable, like
she had something gross on her face and no one was telling her.
Determined to join whatever skeezy club Baron Knight readers enjoyed,
she cracked open the book and read.

Baron Knight was responding to rumours of monsters in rural
France—evidently he was some sort of expert on monsters. Before the
first chapter ended he was surrounded by five demonic wolves, which he
would dispatch with his bare hands by the middle of chapter two. He made
atrocious puns the wolves didn't seem to appreciate and which flew above
the heads of the dim-witted villagers he would later rescue from
similarly unnatural wolves.

The characters were shallow and the plot poorly planned, but the world
seemed eerily real. Cor and Natt alternated serving customers and she
managed to burn through a good quarter of the book before her shift
ended. Baton Knight was on his way to investigate a mysterious cult
outside the village and she was on her way to go lie on a couch for 3
hours.

“How dressed up should I be?”

“I'm going to wear a band shirt and jeans.”

“I see. I'll work from that.”

“See you at 5.”

When she got in the door she stripped down to shower, even though work
had not been particularly strenuous. She put on a purple dress she never
got to wear—simple but pretty, and perfectly casual or semi-formal as
the situation demanded.

Natt didn't want to bother with make up and her hair dried straight,
just the way she liked. She would have preferred curls, but not enough
to justify the effort. Instead she could look at short curly hair like
Rose's and appreciate it vicariously..

Left to her own devices, she collapsed on her couch and read.

When Baron Knight reached the cultists, the head cultist accused him of
standing in the way of progress.

“No progress can be made while you're so blatantly infected.”

“Infected by what?” The cultist asked, as if humouring a child.

Baron Knight pointed at the glowing trunk in the middle of their cave,
massive, ancient, and emitting demonic magic.

“Infected by the Tree.”

Natt shut the book and tossed it away.

Infected by the Tree.

The God in her veins was silent now, not offering any connection between
Itself and this trashy piece of fiction. Or quasi-fiction, at least.

She checked her phone for the time and decided to go for it. Flats on
feet, book in purse, she darted out the door.

It was 15 minutes either way and she debated whom she'd visit. Cor had
known about the books, but if their boss was back they could hardly talk
about them until he was off, which wasn't for another two hours.

So as she stepped into the bookshop she was relieved to find it empty as
ever.

“Back again?” Rose asked, looking up from an open book on her counter.
“How was it?” She looked over Natt's dress with approval.

Natt blushed and said, “I haven't finished yet.” She walked up to the
counter and tried to remember her plan of attack but Rose's eyes,
familiar but all the wrong colour, made her forget everything.

“Oh, pity. Good so far, though?”

“Yeah, yeah. Tacky, but good.”

“That about sums it up. Where are you at?”

“Uh, he's at the cultists in that cave.”

“Oh, yeah. That fight is absurd.” She smiled and Natt tried to smile
back, but the other girl's lips curved with ease and her eyes glittered
with something bordering magic. And Natt... well, she couldn't see
herself but she imagined she was basically the antithesis of visual
charm.

“Listen, you know that bit where he says, ‘you're infected by the Tree’,
does he ever mention... other kinds of infections?”

Rose asked slowly, “Like what other kinds?”

“Ah, like... Metal. Or Lies. ‘Infected by Lies’ or something like that.”

“Any others?”

She looked at the ceiling. “No? Just those three. Trees, Lies, Metal.”

CORRUPT AND DESTROY

Natt shook, the voice a rattling command in the centre of her head. Rose
stepped around the counter and touched her arm. Her hand felt cool and
calming, and for a moment her head was clear and her own. But she
couldn't recall a thing before the hot, damp of the God returned to her.

“How did you—”

“I don't think you're well,” Rose said, walking off to the front door.
Natt raised a hand after her, the voice in her head returning in full
force.

CORRUPT AND DESTROY

“I have teas at my place that might make you feel better.”

Her heart skipped and Natt couldn't speak.

“I was just about to close anyways.”

“Your sister,” she managed. Her voice was a croak, her blood was
rushing.

“Oh, don't worry, I can see her another day. She'll understand.”

Rose locked the door and flipped the OPEN sign to CLOSED. She returned
and grabbed her by the hand, filling her again with a sort of inner
peace.

(corrupt and destroy)

The voice was barely an echo, no life-altering presence but a mere
nuisance to be dealt with in good time.

“Just out the back.”

“Lead on.”

(corrupt and destroy)

Rose kept hold of her hand and the voice remained partially muted, if
not gone entirely. Her home was nearby, a cute cottage-like thing
surrounded by plants and dominated by a large ash tree in the front
yard.

“You live on your own?”

“Yes.”

“How—” She wanted to ask how she could afford this home and the shop,
but it seemed rude. “How long have you been here?”

“About 9 years now. Time really flies, huh?”

“Yeah.” Natt looked at the tree as Rose fished for keys. Had the tree in
the cultist's cave been an ash? She couldn't remember, but it didn't
seem wrong.

“Forgive the mess,” she said, ushering her guest past piles of books
into the kitchen which was in a similar state. The whole thing seemed an
extension of her store if it had been overrun by potted and hanging
plants. “I love your dress, by the way. It makes you look so pretty.”

“Oh, thanks,” she mumbled. Rose sat her down at a wooden table with 3
wooden chairs. She filled an electric kettle and plugged it in. One
cupboard was full of teas and she pulled out two bags full of purple
crystals the colour of Natt's dress and the colour of Rose's hair.

“Oh, we match,” she said, instantly hating herself for her own inanity.

But Rose gave a small laugh. “It really is my favourite colour.” She sat
down and folded her hands in front of her. “So.”

“So?”

“How long have you been hearing voices?”

“Oh! What? I never—” Rose held up a hand and shook her head.

“Let's be honest. You've got some sort of fluid parasite in you making
weird requests, right?”

“Yes. Yes I do.” She narrowed her eyes, but Rose simply smiled.

CORRUPT AND DESTROY

Rose wasn't angry or frightened or even particularly concerned. This was
just an everyday thing, apparently, having a God in your veins. She took
in a deep breath and let it out. It felt like an absurd burden was being
peeled off of her back. She could get back to normal, whatever that was.
She could accept this. She could accept me.

CORRUPT AND DESTROY

“I don't remember how long I've been stuck with this... do you know how
to make it better?”

“Just a cup of tea.”

“Really?”

“Really.”

“Did you have this too?”

“Oh, no, I've just been told about it. I've seen the other infections
though.”

The kettle began to whistle and Rose unplugged it, pouring it into two
mugs. She plopped a bag into each and belatedly asked, “Oh, sorry, do
you want milk or sugar?”

“Oh, no, thanks.”

DO NOT CONSUME

“It doesn't want me drinking this.”

Rose set the mug in front of her and grabbed her hand. “Well of course
it doesn't. It will kill the creature inside you.”

(do not consume do not consume do not consume)

The voice was a murmur, insistent but distant like a television on in
another room. Natt looked at the drink and sighed. This is what she
wanted, right? To be normal?

(do not consume do not consume do not consume)

What had It actually done for her? Nothing. It made promises, sure, but
would it actually fulfil them? Was it even capable of that?

“Can It... actually give me super strength and stuff?” she asked,
feeling stupid for bothering. The steaming water in front of her turned
a purple so dark it was almost black. It made her think of the stretch
of sky just before night.

The other girl sighed. “I won't lie. There are stories that it can be
done, although I've never seen it.”

(do not consume do not consume do not consume)

Rose ran her hand up and down Natt's arm.

“You're... making the voice quieter. How do you do that?”

“I'm a servant of the Trees.”

She pulled back her arm. “Infected by the Trees, you mean.” She shook
her head. Why did she think that? All she knew about it was from a
poorly written book.

CORRUPT DESTROY CORRUPT DESTROY

“The Trees don't live inside us, and They don't change who we are or
make demands of us. We wilfully enter Their service, and They share
Their gifts with us.” Rose shifted her chair closer until it was next to
hers, and leaned in. “You're sick but together we can make you better.”

Rose reached for her hand slowly, looking for permission. Natt nodded
and held out her hand. The other girl took it and raised it to her lips,
kissing it. It was a gentle, nurturing kiss that made her shiver.

“Can... can we keep this up? After?”

“You can stay here forever.” Rose kissed her hand again.

(do not consume)

The voice was the rustle of leaves in a forest, impotent and
inconsequential. The tea was warm, strangely viscous and smelled of
something sweet and metallic.

“This is all it takes?”

“That's all.”

Natt raised her mug and looked expectantly at Rose. She shook her head
but raised the mug. “To new beginnings.”

“To new beginnings.”

Rose sipped her drink and Natt followed suit. Her stomach grumbled but
Rose told her it was part of the process. She nodded.

“So what is It called? The Thing inside me?”

“A parasite. Specifically, it's ‘Ooze’. A silly name, I know, but when
It's without a host It rather looks like... well, oozing gunk, really.”

“So that's the end of the pattern then? Metal, Trees, Lies, and Ooze?”

“Oh, no. ‘Blood’ is the word most often used. People tend to avoid using
Their actual names.”

Natt drank from her mug and grimaced. The sweetness left an aftertaste
of decay, and in the back of her head something was crying out in anger.
The word ‘Blood’ seemed ominous as her entire body began to burn like a
furnace. The God in her veins made her feverish on the best of days, but
this was a shamanistic sweat that was simultaneously threatening and
liberating.

The tree outside tapped on the window. It seemed to mock her even as the
God in her veins screamed. But Rose squeezed her hand and refused to let
go. Natt closed her eyes. She pictured a life with this girl. Helping
others who found themselves cursed. She downed the last of her tea and
coughed. Her mouth was dry and her insides felt like dust.

“How... how long?”

“Moments, now.”

Natt tried to breathe but her lungs wouldn't respond. She wheezed and
collapsed to the ground. Her right hand hung above her, still held tight
by Rose.

“I'm sorry it has to be this way,” she said. Her eyes were damp, tears
dripping down her cheeks onto Natt's face. Natt struggled feebly, but as
her chest got tighter she eventually gave up.

“The dust in the tea kills the parasite, but not before It wrecks your
insides. It doesn't seem to go without a fight, and it's the fight that
kills you in the end. I'm sorry.”

The God in Natt's veins had promised her all manner of things, but
all it had given her was death. She outlived the parasite by seconds,
but that was enough. Her spirit was saved, and would be offered to the
Trees where she would be at rest.

Rose finally released Natt's hand, letting it fall to the floor.

The Trees took one of many forms in her front yard, and It seemed to
beckon infected to this town without a conscious understanding of why.
Rose could never be sure when another would come her way, but she'd been
given enough poisons to last a lifetime, surely.

Most infected had to be tricked or forced into parting with their
parasites, but Natt had come for answers and taken her cure willingly.
Rose was sorry for the girl’s death, but there was nothing to be done
for it now.

In her well-sheltered backyard where ash roots still reached, four
graves held the bodies of four infected. Three infected by Lies, one
infected by Metal, and now she'd need a fifth hole for one infected by
Blood. They would have said Rose was infected by Trees, but they didn’t
understand the true order of things. The Trees stood between humanity
and infection.

The God in Natt's veins was no match for the God in Rose's yard.
